-- EXEMPLO – FUNÇÕES DE DATA 
SELECT DT_ADMISSAO ,
       TO_CHAR(DT_ADMISSAO, 'YYYY')     "ANO CONTRATACAO"       ,
        TO_CHAR(DT_ADMISSAO, 'MM/YYYY') "MÊS E ANO CONTRATACAO"  ,
        TO_CHAR(DT_ADMISSAO, 'DD/MM') "DIA E MÊS DA CONTRATACAO" ,
        TO_CHAR(DT_ADMISSAO, 'DD " de " fmMONTH " de " YYYY', 'NLS_DATE_LANGUAGE=PORTUGUESE') "DATA POR EXTENSO"
  FROM T_SIP_FUNCIONARIO;

  -- EXEMPLO – FUNÇÕES DE DATA 
 SELECT DT_ADMISSAO ,
        TO_DATE(DT_ADMISSAO , 'DD/MM/YYYY') - 5,
        TO_DATE(SYSDATE, 'DD/MM/YYYY') - TO_DATE(DT_ADMISSAO, 'DD/MM/YYYY')
  FROM  T_SIP_FUNCIONARIO;


  -- EXEMPLO – FUNÇÕES DE DATA 
 SELECT DT_ADMISSAO ,
        TO_DATE(DT_ADMISSAO,'DD/MM/YYYY HH:MI:SS') + 6/24
   FROM T_SIP_FUNCIONARIO;