-- EXEMPLO – FUNÇÕES NUMÉRICAS
SELECT F.VL_SALARIO           ,
       ROUND(F.VL_SALARIO)    ,
       ROUND(F.VL_SALARIO,1)  ,
       TRUNC(F.VL_SALARIO)    ,
       TRUNC(F.VL_SALARIO,1)  ,
       MOD(F.VL_SALARIO,3)    ,
       ABS(F.VL_SALARIO)      ,
       SQRT(F.VL_SALARIO)
      FROM T_SIP_FUNCIONARIO F;


      -- EXEMPLO – FUNÇÕES DE CONVERSÃO – TO_CHAR()
SELECT F.VL_SALARIO ,
       TO_CHAR(F.VL_SALARIO, 'L9999999.99') "SIMBOLO MOEDA LOCAL" ,
       TO_CHAR(F.VL_SALARIO, 'C99,999.99') "SIMBOLO MOEDA ISO" ,
       TO_CHAR(F.VL_SALARIO, '99,999.99')  ,
       F.NR_MATRICULA ,
       TO_CHAR(F.NR_MATRICULA, '0099999')       
  FROM T_SIP_FUNCIONARIO F;


  -- EXEMPLO – FUNÇÕES DE CONVERSÃO – TO_NUMBER()
SELECT TO_NUMBER('103')      ,
       TO_NUMBER('103') + 30 ,
       TO_NUMBER('-$12,345.99','$99,999.99')
  FROM DUAL;

  -- EXEMPLO – FUNÇÕES DE CONVERSÃO – TO_DATE()
SELECT F.DT_ADMISSAO ,
       TO_DATE(F.DT_ADMISSAO,'DD/MM/YYYY')  
  FROM T_SIP_FUNCIONARIO F;

  -- EXEMPLO – FUNÇÕES DE CONVERSÃO – CAST()
-- CONVERTER VALORES LITERAIS EM TIPOS ESPECÍFICOS
SELECT 
        CAST( 12345.67 AS VARCHAR2(10) ) ,        
        CAST( '29/09/2013' AS DATE )     ,
        CAST( 12345.678 AS NUMBER(10,2)) 
  FROM DUAL;

  -- EXEMPLO – FUNÇÕES DE CONVERSÃO – CAST()
-- CONVERTER VALORES DE COLUNA DE UM TIPO PARA OUTRO
SELECT 
       CAST ( F.VL_SALARIO AS VARCHAR2(10) ) ,
       CAST ( F.VL_SALARIO + 1000 AS NUMBER (8,2) )
  FROM T_SIP_FUNCIONARIO F;