-- EXEMPLO – FUNÇÕES LOWER(), UPPER() e INITCAP()
SELECT F.NM_FUNCIONARIO           "COMO ESTÁ GRAVADO"  ,
 LOWER(F.NM_FUNCIONARIO)    "MINUSCULAS (LOWER)" ,
 UPPER(F.NM_FUNCIONARIO)    "MAIUSCULAS (UPPER)" ,
 INITCAP(F.NM_FUNCIONARIO)  "MAIUSCULA/MINUSCULA (INITCAP)"      
  FROM T_SIP_FUNCIONARIO F;


  -- EXEMPLO – FUNÇÕES ASCII() e CHR()
SELECT ASCII('R'), 
       CHR(82) 
  FROM DUAL;

  -- EXEMPLO – FUNÇÃO CONCAT()
SELECT CONCAT(CONCAT(F.NR_MATRICULA,'-'),F.NM_FUNCIONARIO)           
  FROM T_SIP_FUNCIONARIO F;


  -- EXEMPLO – FUNÇÃO INSTR()
SELECT F.NM_FUNCIONARIO                ,
       INSTR(F.NM_FUNCIONARIO,'A')     ,
       INSTR(F.NM_FUNCIONARIO,'JOS')   ,
       INSTR(F.NM_FUNCIONARIO,'A',3)   ,
       INSTR(F.NM_FUNCIONARIO,'A',3,2)
  FROM T_SIP_FUNCIONARIO F;


  -- EXEMPLO – FUNÇÃO LENGTH ()
SELECT F.NM_FUNCIONARIO , 
       LENGTH(F.NM_FUNCIONARIO)    
  FROM T_SIP_FUNCIONARIO F;

  -- EXEMPLO – FUNÇÕES RPAD() e LPAD()
SELECT F.NM_FUNCIONARIO                ,
       F.VL_SALARIO                    ,
       RPAD(F.NM_FUNCIONARIO,60)       ,
       RPAD(F.NM_FUNCIONARIO,60,'.')   ,
       LPAD(F.VL_SALARIO,10,'*')   
  FROM T_SIP_FUNCIONARIO F;

  -- EXEMPLO – FUNÇÕES RTRIM(), LTRIM() E TRIM()
SELECT D.NM_DEPTO        ,
       LTRIM(D.NM_DEPTO) ,
       TRIM(D.NM_DEPTO)
       FROM T_SIP_DEPARTAMENTO D;

       -- EXEMPLO – FUNÇÕES RTRIM(), LTRIM() E TRIM()
SELECT F.NM_FUNCIONARIO                ,       
       LTRIM(F.NM_FUNCIONARIO, 'A')    ,       
       RTRIM(F.NM_FUNCIONARIO, 'O')    ,             
       TRIM('A' FROM F.NM_FUNCIONARIO)     
  FROM T_SIP_FUNCIONARIO F;

  -- EXEMPLO – FUNÇÕES NVL() e NVL2()
SELECT F.DT_NASCIMENTO                   ,
       NVL(F.DT_NASCIMENTO,'01/01/1900') ,
       NVL2(F.DT_NASCIMENTO,SYSDATE,'01/01/1900')       
  FROM T_SIP_FUNCIONARIO F;

  -- EXEMPLO – FUNÇÃO REPLACE()
SELECT F.NM_FUNCIONARIO                ,
       REPLACE(F.NM_FUNCIONARIO,'A','*')
  FROM T_SIP_FUNCIONARIO F;

  -- EXEMPLO – FUNÇÃO SUBSTR()
SELECT F.NM_FUNCIONARIO                ,
       SUBSTR(F.NM_FUNCIONARIO,3)      ,
       SUBSTR(F.NM_FUNCIONARIO,3, 5)      
  FROM T_SIP_FUNCIONARIO F;